document.write( '<link rel=\"stylesheet\" href=\"css/paytab.css\">\n' );
document.write( '<script src="https://www.paytabs.com/theme/express_checkout/js/jquery-1.11.1.min.js\"></script>\n' );
document.write( '<script src=\"https://www.paytabs.com/express/express_checkout_v3.js\"></script>\n' );
document.write( '<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n' );
document.write( '<div class=\"PT_express_checkout\"></div>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( ' \n' );
document.write( ' Paytabs(\"#express_checkout\").expresscheckout({\n' );
document.write( ' settings:{\n' );
document.write( ' merchant_id: \"10032091\",\n' );
document.write( ' secret_key: \"347SeeN6Pitf5fBIUsr4ZV8B4MTP8XCc2J4gXSmNaP3f5EY07q46ldHq0Bf9ySlACpQAhcns2rI86G8d6cjsq1SqD7zbZVMClCcD\",\n' );
document.write( ' amount : \"10.00\",\n' );
document.write( ' currency : \"USD\",\n' );
document.write( ' title : \"Mr. John Doe\",\n' );
document.write( ' product_names: \"Product1,Product2,Product3\",\n' );
document.write( ' order_id: 25,\n' );
document.write( ' url_redirect: \"http://localhost:9000/checkout\",\n' );
document.write( ' display_customer_info:1,\n' );
document.write( ' display_billing_fields:1,\n' );
document.write( ' display_shipping_fields:0,\n' );
document.write( ' language: \"en\",\n' );
document.write( ' redirect_on_reject: 1,\n' );
document.write( ' style: {\n' );
document.write( ' css: \"custom\",\n' );
document.write( ' linktocss: \"http://localhost:9000/css/paytab.css\",\n' );
document.write( ' },\n' );
document.write( '\n' );
document.write( ' is_iframe: {\n' );
document.write( ' load: \"onbodyload\", \n' );
document.write( ' },\n' );
document.write( '\n' );
document.write( ' },\n' );
document.write( '\n' );
document.write( 'customer_info:{\n' );
document.write( ' first_name: \"John\",\n' );
document.write( ' last_name: \"Smith\",\n' );
document.write( ' phone_number: \"5486253\",\n' );
document.write( ' email_address: \"john@test.com\",\n' );
document.write( ' country_code: \"973\"\n' );
document.write( ' },\n' );
document.write( ' billing_address:{\n' );
document.write( ' full_address: \"Manama, Bahrain\",\n' );
document.write( ' city: \"Manama\",\n' );
document.write( ' state: \"Manama\",\n' );
document.write( ' country: \"BHR\",\n' );
document.write( ' postal_code: \"00973\"\n' );
document.write( ' },\n' );
document.write( ' shipping_address:{\n' );
document.write( ' shipping_first_name: \"Jane\",\n' );
document.write( ' shipping_last_name: \"Abdulla\",\n' );
document.write( ' full_address_shipping: \"Manama, Bahrain\",\n' );
document.write( ' city_shipping: \"Manama\",\n' );
document.write( ' state_shipping: \"Manama\",\n' );
document.write( ' country_shipping: \"BHR\",\n' );
document.write( ' postal_code_shipping: \"00973\"\n' );
document.write( ' },\n' );
document.write( ' checkout_button:{\n' );
document.write( 'width: 150,\n' );
document.write( 'height: 30,\n' );
document.write( 'img_url: \"https://www.YOURWEBSITE.com/image/yourimage.jpg\"\n' );
document.write( '},\n' );
document.write( ' \n' );
document.write( ' pay_button:{\n' );
document.write( ' width: 150,\n' );
document.write( ' height: 30,\n' );
document.write( ' \n' );
document.write( ' }\n' );
document.write( '\n' );
document.write( ' });\n' );
document.write( '</script>\n' );
